using System.Text;
using BlogMlToWxr.Configuration;
using BlogMlToWxr.Models;

namespace BlogMlToWxr.Writing;

/// <summary>
/// Produces the old to new URL map in two formats:
/// redirects.csv for the Redirection plugin, and redirects.htaccess for Apache level 301s.
/// </summary>
public sealed class RedirectWriter
{
    private readonly MigrationOptions _options;

    public RedirectWriter(MigrationOptions options) => _options = options;

    public (string CsvPath, string HtaccessPath, int Count) Write(BlogData blog)
    {
        Directory.CreateDirectory(_options.OutputDirectory);

        var csv = new StringBuilder("source,target,match_type,action_code\n");
        var htaccess = new StringBuilder();
        htaccess.AppendLine("# Generated by BlogMlToWxr. Paste above the WordPress rewrite block in .htaccess.");
        htaccess.AppendLine("<IfModule mod_rewrite.c>");
        htaccess.AppendLine("RewriteEngine On");

        var pairs = new SortedDictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        foreach (var post in blog.Posts)
        {
            var target = _options.NewPostUrlPattern.Replace("{slug}", post.Slug, StringComparison.Ordinal);

            foreach (var source in BuildSourceUrls(post))
            {
                if (string.IsNullOrWhiteSpace(source)) continue;
                if (source.Equals(target, StringComparison.OrdinalIgnoreCase)) continue;
                pairs[source] = target;
            }
        }

        foreach (var pair in pairs)
        {
            csv.Append(Escape(pair.Key)).Append(',')
               .Append(Escape(pair.Value)).Append(",url,301\n");

            htaccess.Append("RewriteRule ^")
                    .Append(pair.Key.TrimStart('/').Replace(".", "\\.", StringComparison.Ordinal))
                    .Append("$ ")
                    .Append(pair.Value)
                    .AppendLine(" [R=301,L]");
        }

        // Feed and search handlers that BlogEngine exposed.
        htaccess.AppendLine("RewriteRule ^syndication\\.axd$ /feed/ [R=301,L]");
        htaccess.AppendLine("RewriteRule ^search\\.aspx$ /?s= [R=301,L]");
        htaccess.AppendLine("RewriteRule ^archive\\.aspx$ /archives/ [R=301,L]");
        htaccess.AppendLine("</IfModule>");

        csv.Append("/syndication.axd,/feed/,url,301\n");

        var csvPath = Path.Combine(_options.OutputDirectory, "redirects.csv");
        var htaccessPath = Path.Combine(_options.OutputDirectory, "redirects.htaccess");

        File.WriteAllText(csvPath, csv.ToString(), new UTF8Encoding(false));
        File.WriteAllText(htaccessPath, htaccess.ToString(), new UTF8Encoding(false));

        return (csvPath, htaccessPath, pairs.Count);
    }

    private IEnumerable<string> BuildSourceUrls(BlogPost post)
    {
        var results = new List<string>();

        if (!string.IsNullOrWhiteSpace(post.OriginalUrl))
        {
            var path = post.OriginalUrl;

            if (Uri.TryCreate(path, UriKind.Absolute, out var absolute))
                path = absolute.AbsolutePath;

            if (!path.StartsWith('/')) path = "/" + path;
            results.Add(path);
        }

        // BlogEngine default permalink shapes.
        results.Add($"/post/{post.Slug}.aspx");
        results.Add($"/post/{post.DateCreated:yyyy/MM/dd}/{post.Slug}.aspx");

        if (Guid.TryParse(post.Id, out var guid))
            results.Add($"/post.aspx?id={guid}");

        return results.Distinct(StringComparer.OrdinalIgnoreCase);
    }

    private static string Escape(string value) =>
        value.Contains(',') || value.Contains('"')
            ? "\"" + value.Replace("\"", "\"\"", StringComparison.Ordinal) + "\""
            : value;
}
